### ISSUE TITLE
How to add?

### ISSUE THREAD

**Issue by julianfairfax** [alex-gutev/oaproxy#2]
GNOME Online Accounts says the server doesn't support PLAIN. I don't have any options to change this. Geary says to check my receiving login and password. The proxy is running, but doesn't seem to support either method of adding an account?

**Comment by alex-gutev** [comment]
You have to set up your GNOME online account as OAUTH2, thats the part which communicates with the actual mail server. Geary has to be set up to communicate with the local proxy server. It is here where you have to set PLAIN authentication.

**Comment by julianfairfax** [comment]
> You have to set up your GNOME online account as OAUTH2, thats the part which communicates with the actual mail server. Geary has to be set up to communicate with the local proxy server. It is here where you have to set PLAIN authentication.

GNOME online accounts doesn't support OAUTH2. i thought the purpose of this tool was to bridge the gap between OAUTH2 servers and non-OAUTH2 clients

**Comment by alex-gutev** [comment]
GOA (GNOME online accounts) does support OAUTH2, at least for specific email providers, for example you can add a Google account and use this tool to access Gmail from a non-OAUTH2 client. That is the purpose of this tool however it is GOA which actually takes care of the OAUTH2 part, and thus you're limited to the email providers supported by GOA. In the future I may bypass GOA and communicate with the email providers directly.

**Comment by julianfairfax** [comment]
> GOA (GNOME online accounts) does support OAUTH2, at least for specific email providers, for example you can add a Google account and use this tool to access Gmail from a non-OAUTH2 client. That is the purpose of this tool however it is GOA which actually takes care of the OAUTH2 part, and thus you're limited to the email providers supported by GOA. In the future I may bypass GOA and communicate with the email providers directly.

So it is somehow possible to accessible a Microsoft 365 account through this proxy and some GOA option?

**Comment by julianfairfax** [comment]
I require that account for school, but Geary and GOA don't support OAUTH on them.

**Comment by alex-gutev** [comment]
There are two options in GOA account settings, you can either add a Microsoft account, which seems to be a Microsoft live account, or a Microsoft exchange account. Maybe one of them can work for you.

I've added a screenshot.

![Screenshot from 2022-12-15 19-00-16](https://user-images.githubusercontent.com/20755596/207934260-3c3013aa-d021-4540-93e1-bf677d4a340c.png)

**Comment by julianfairfax** [comment]
Neither of those will work because the Microsoft one requires a personal account, and the Exchange one an Exchange server. I'm still not understanding how or if you're supposed to use oaproxy in this case, as even the Google option doesn't allow you specify any custom server, like localhost:3001, and the IMAP and SMTP option doesn't work with it.

**Comment by alex-gutev** [comment]
I see. I haven't tried it with Microsoft accounts, so I don't how useful it is there.

You don't specify the custom localhost server in the Google or Microsoft account option, when setting up a GOA account. You specify it in Geary, or whichever email client you use, since it is the email client which needs to connect with the local oaproxy server. The oaproxy localhost server performs authentication via OAuth2 using the GOA account and then merely forwards all requests to and from between the email client and Microsoft/Google servers.

In short your email client talks to oaproxy (localhost:3001 or whatever you have set) using plain authentication. Oaproxy talks to the mail provider and performs OAuth2 authentication using a GNOME online account that you have configured in the settings screen that I showed in the screenshot.

As to when you should use it. It's useful if your email client doesn't support OAuth2 and your email provider only supports OAuth2. If your email provider provides an option other than OAuth2 which is supported by your email client, then that's preferable to using oaproxy. Also if your email client supports OAuth2 then oaproxy is obviously redundant and unnecessary in that case.

Also keep in mind this is an experimental project.

**Comment by julianfairfax** [comment]
> I see. I haven't tried it with Microsoft accounts, so I don't how useful it is there.
> 
> You don't specify the custom localhost server in the Google or Microsoft account option, when setting up a GOA account. You specify it in Geary, or whichever email client you use, since it is the email client which needs to connect with the local oaproxy server. The oaproxy localhost server performs authentication via OAuth2 using the GOA account and then merely forwards all requests to and from between the email client and Microsoft/Google servers.
> 
> In short your email client talks to oaproxy (localhost:3001 or whatever you have set) using plain authentication. Oaproxy talks to the mail provider and performs OAuth2 authentication using a GNOME online account that you have configured in the settings screen that I showed in the screenshot.
> 
> As to when you should use it. It's useful if your email client doesn't support OAuth2 and your email provider only supports OAuth2. If your email provider provides an option other than OAuth2 which is supported by your email client, then that's preferable to using oaproxy. Also if your email client supports OAuth2 then oaproxy is obviously redundant and unnecessary in that case.
> 
> Also keep in mind this is an experimental project.

In that case it's impossible to use this with a school's Microsoft 365 account, as you can't add it through GNOME Online Accounts
